# Project Information
site_name: Field Notes
site_author: Damita Salmon
site_url: https://iruldanet.gitlab.io/field-notes
site_dir: public
site_description: A collection of tech notes and lab write-ups, for my own reference.

#Repository
#repo_url: https://gitlab.com/iruldanet/field-notes
#repo_name: iruldanet/field-notes

#Configuration
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: purple
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.top
  icon:
    repo: fontawesome/brands/gitlab

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md
  - glightbox
  
# Extensions
markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - footnotes
  - attr_list
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji



# Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/damitasalmon
  generator: false

extra_css:
  - assets/stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2023 Damita Salmon
